ALTER TABLE asset
    ADD COLUMN filename VARCHAR(255) NOT NULL DEFAULT '' AFTER path,
    ADD COLUMN original_name VARCHAR(255) NOT NULL DEFAULT '' AFTER filename,
    ADD COLUMN size BIGINT NOT NULL DEFAULT 0 AFTER original_name,
    ADD COLUMN mime_type VARCHAR(127) NOT NULL DEFAULT '' AFTER size,
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER mime_type;

ALTER TABLE project
    ADD COLUMN cover_asset_id INT UNSIGNED NULL AFTER data,
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER cover_asset_id,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
